;;;; test-corpus.lisp — Tests for discovery, lookup, show, index, and next

(in-package #:compass.tests)

(def-suite corpus :in compass)
(in-suite corpus)

(defparameter *sample-files*
  (list (list "Compass.md" (doc :id "TEST-0001" :genre "Spec" :status "Draft"
                                :body (lines "# Standard" "## Scope" "In scope.")))
        (list "README.md" (lines "# Readme, a fixture without front-matter"))
        (list "doc/README.md" (lines "# Doc readme"))
        (list "doc/INDEX.md" (lines "<!-- generated -->"))
        (list "doc/Plan.A.md"
              (doc :id "TEST-DRAFT-alpha"
                   :extra '("decisions:" "  - TEST-DRAFT-alpha-D1" "  - TEST-D3")
                   :body (lines "# Alpha" "## Settled Decisions" ""
                                "### TEST-DRAFT-alpha-D1 — Use a ledger" ""
                                "**Status:** Accepted" "" "Because."
                                "" "### TEST-D3 — An older decision" ""
                                "**Status:** Accepted" "" "## Roadmap" "1. Build.")))
        (list "doc/sub/Log.B.md" (doc :id "TEST-0004" :genre "Log" :status "Accepted"))))

(test discovery
  (with-temp-repository (root *sample-files*)
    (let ((corpus (load-corpus root)))
      (is (equal '("Compass.md" "doc/Plan.A.md" "doc/sub/Log.B.md")
                 (mapcar #'document-path (corpus-documents corpus))))
      (is (null (corpus-load-findings corpus)))
      (is (equal '("TEST") (corpus-namespaces corpus))))))

(test repository-root
  (with-temp-repository (root (list (list "compass.sexp" "(:namespaces (\"TEST\"))")
                                    (list "doc/deep/x.md" "x")))
    (is (uiop:pathname-equal root
                             (find-repository-root (merge-pathnames "doc/deep/" root))))))

(test lookup-and-resolve
  (with-temp-repository (root *sample-files*)
    (let ((corpus (load-corpus root)))
      (is (equal "doc/Plan.A.md" (document-path (find-document corpus "TEST-DRAFT-alpha"))))
      (is (equal "Use a ledger" (record-title (find-record corpus "TEST-DRAFT-alpha-D1"))))
      (is (typep (resolve corpus "TEST-0001#scope") 'section))
      (is (null (resolve corpus "TEST-0001#nowhere")))
      (is (null (resolve corpus "TEST-0099"))))))

(test show-text
  (with-temp-repository (root *sample-files*)
    (let ((corpus (load-corpus root)))
      (multiple-value-bind (text path first last) (show corpus "TEST-DRAFT-alpha-D1")
        (is (equal "doc/Plan.A.md" path))
        (is (= 17 first))
        (is (= 21 last))
        (is (starts-with-p "### TEST-DRAFT-alpha-D1 — Use a ledger" text))
        (is (search "Because." text))
        (is (not (search "older decision" text))))
      (multiple-value-bind (text) (show corpus "TEST-0001#scope")
        (is (equal (lines "## Scope" "In scope.") text)))
      (is (null (show corpus "TEST-0404"))))))

(test index-generation
  (with-temp-repository (root *sample-files*)
    (let* ((corpus (load-corpus root))
           (text (generate-index corpus)))
      (is (starts-with-p "<!-- Generated by `compass index`" text))
      (is (search "| [TEST-0001](../Compass.md) |" text))
      (is (search "| [TEST-0004](sub/Log.B.md) |" text))
      (is (search "Table: Documents in the TEST namespace." text))
      (is (search "[TEST-D3](Plan.A.md#test-d3--an-older-decision)" text))
      ;; Canonical identifiers come before provisional ones.
      (is (< (search "TEST-0004" text) (search "TEST-DRAFT-alpha]" text)))
      (is (equal "doc/INDEX.md" (write-index corpus)))
      (is (equal text (read-text-file (root-file root "doc/INDEX.md"))))
      ;; The index is not a document, and its links resolve.
      (let ((after (load-corpus root)))
        (is (= 3 (length (corpus-documents after))))
        (is (null (check-corpus after)))))))

(test next-identifier-is-advisory
  (with-temp-repository (root *sample-files*)
    (let ((corpus (load-corpus root)))
      (multiple-value-bind (id advisory) (next-identifier corpus "TEST" :document)
        (is (equal "TEST-0005" id))
        (is-true advisory))
      (is (equal "TEST-D4" (next-identifier corpus "TEST" :decision)))
      (is (equal "TEST-M1" (next-identifier corpus "TEST" :memo)))
      (is (equal "OTHER-0001" (next-identifier corpus "OTHER" :document))))))
