;;;; test-cli.lisp — Tests for the command line: exit codes, output formats, and usage errors

(in-package #:compass.tests)

(def-suite cli :in compass)
(in-suite cli)

(test check-exit-codes
  (with-temp-repository (root (list (list "doc/Plan.A.md" (doc :created "2026-10-09"))))
    (multiple-value-bind (code out) (run-cli "check" (root-arg root))
      (is (= 0 code))
      (is (search "Checked 1 document: 0 errors, 0 warnings." out))))
  (with-temp-repository (root (list (list "doc/Plan.A.md" (doc :genre "Nonsense"))))
    (multiple-value-bind (code out) (run-cli "check" (root-arg root))
      (is (= 1 code))
      (is (search "doc/Plan.A.md:4:8: error vocab/genre:" out))))
  (with-temp-repository (root (list (list "doc/Plan.A.md" (doc :created "2026-10-09"
                                                              :extra '("colour: blue")))))
    (is (= 0 (run-cli "check" (root-arg root))))
    (is (= 1 (run-cli "check" "--strict" (root-arg root))))))

(test check-json
  (with-temp-repository (root (list (list "doc/Plan.A.md" (doc :scope "team"
                                                              :created "2026-10-09"))))
    (multiple-value-bind (code out) (run-cli "check" "--format" "json" (root-arg root))
      (is (= 1 code))
      (let* ((json (shasht:read-json out))
             (findings (gethash "findings" json)))
        (is (equal "compass" (gethash "tool" json)))
        (is (= 1 (gethash "errors" (gethash "summary" json))))
        (is (equal "vocab/scope" (gethash "rule" (aref findings 0))))
        (is (equal "doc/Plan.A.md" (gethash "path" (aref findings 0))))))))

(test check-rule-selection-and-paths
  (with-temp-repository (root (list (list "doc/Plan.A.md" (doc :scope "team"
                                                              :created "2026-10-09"))
                                    (list "doc/Plan.B.md" (doc :id "TEST-0002"
                                                               :genre "Nonsense"
                                                               :created "2026-10-09"))))
    (is (= 1 (run-cli "check" "--rule" "vocab/scope" (root-arg root))))
    (is (= 0 (run-cli "check" "--rule" "fm" (root-arg root))))
    (is (= 0 (run-cli "check" "--exclude" "vocab" (root-arg root))))
    (let ((*default-pathname-defaults* root))
      (multiple-value-bind (code out)
          (run-cli "check" (root-arg root)
                   (uiop:native-namestring (merge-pathnames "doc/Plan.A.md" root)))
        (is (= 1 code))
        (is (not (search "Plan.B.md" out)))))))

(test show-and-next
  (with-temp-repository (root (list (list "doc/Plan.A.md" (doc :body (lines "# T" "## Part" "Text.")))))
    (multiple-value-bind (code out) (run-cli "show" "TEST-0001#part" (root-arg root))
      (is (= 0 code))
      (is (search (lines "## Part" "Text.") out)))
    (multiple-value-bind (code out err) (run-cli "show" "TEST-0404" (root-arg root))
      (is (= 1 code))
      (is (string= "" out))
      (is (search "not defined" err)))
    (multiple-value-bind (code out err) (run-cli "next" "TEST" (root-arg root))
      (is (= 0 code))
      (is (equal (lines "TEST-0002") out))
      (is (search "a preview" err))
      (is (search "there is no ledger" err)))))

(test usage-errors
  (is (= 2 (run-cli)))
  (is (= 2 (run-cli "frobnicate")))
  (is (= 2 (run-cli "check" "--colour")))
  (is (= 2 (run-cli "check" "--format" "xml")))
  (is (= 2 (run-cli "check" "--rule" "no/such-rule")))
  (is (= 2 (run-cli "next" "lowercase")))
  (multiple-value-bind (code out err) (run-cli "check" "--format")
    (declare (ignore out))
    (is (= 2 code))
    (is (search "needs a value" err))))

(test help-version-rules
  (multiple-value-bind (code out) (run-cli "help")
    (is (= 0 code))
    (dolist (command '("check" "show" "outline" "refs" "index" "next" "rules" "version"))
      (is (search (format nil "  ~a " command) out) "help lists ~a" command)))
  (multiple-value-bind (code out) (run-cli "version")
    (is (= 0 code))
    (is (starts-with-p (format nil "compass ~a" +version+) out)))
  (multiple-value-bind (code out) (run-cli "rules" "--format" "json")
    (is (= 0 code))
    (let ((rules (shasht:read-json out)))
      (is (find "memo/basis" rules :key (lambda (r) (gethash "name" r)) :test #'equal))
      (is (find "fm/syntax" rules :key (lambda (r) (gethash "name" r)) :test #'equal)))))

(test check-rejects-paths-outside-the-corpus
  (with-temp-repository (root (list (list "doc/Plan.A.md" (doc :created "2026-10-09"))
                                    (list "doc/Plan.B.md" (doc :id "TEST-0002"
                                                               :created "2026-10-09"))
                                    (list "templates/X.md" (lines "# Not a document"))))
    (flet ((path (relative) (uiop:native-namestring (merge-pathnames relative root))))
      (multiple-value-bind (code out err) (run-cli "check" (root-arg root)
                                                   (path "templates/X.md"))
        (is (= 2 code))
        (is (string= "" out))
        (is (search "templates/X.md is not a document of this corpus" err)))
      (multiple-value-bind (code out err) (run-cli "check" (root-arg root) (path "templates/"))
        (declare (ignore out))
        (is (= 2 code))
        (is (search "contains no documents" err)))
      (multiple-value-bind (code out) (run-cli "check" (root-arg root) (path "doc/Plan.A.md"))
        (is (= 0 code))
        (is (search "Checked 1 document of 2:" out)))
      (multiple-value-bind (code out) (run-cli "check" (root-arg root) (path "doc/"))
        (is (= 0 code))
        (is (search "Checked 2 documents:" out)))
      (with-temp-repository (elsewhere (list (list "doc/Plan.Z.md" (doc))))
        (multiple-value-bind (code out err)
            (run-cli "check" (root-arg root)
                     (uiop:native-namestring (merge-pathnames "doc/Plan.Z.md" elsewhere)))
          (declare (ignore out))
          (is (= 2 code))
          (is (search "outside the repository" err)))))))

(test empty-corpus
  (with-temp-repository (root (list (list "notes.txt" "nothing here")))
    (multiple-value-bind (code out err) (run-cli "check" (root-arg root))
      (is (= 0 code))
      (is (search "Checked 0 documents" out))
      (is (search "no documents found" err)))
    (multiple-value-bind (code out err) (run-cli "index" (root-arg root))
      (declare (ignore out))
      (is (= 2 code))
      (is (search "no index was written" err))
      (is (not (probe-file (merge-pathnames "doc/INDEX.md" root)))))
    (is (= 0 (run-cli "index" "--stdout" (root-arg root))))))

(test outline-command
  (with-temp-repository (root *reference-files*)
    (multiple-value-bind (code out) (run-cli "outline" "TEST-0001" (root-arg root))
      (is (= 0 code))
      (is (search "TEST-0001 — A test document" out))
      (is (search "doc/Plan.A.md; Plan, Draft" out))
      (is (search "### TEST-D1 — Use a ledger  #test-d1--use-a-ledger" out)))
    (multiple-value-bind (code out) (run-cli "outline" "TEST-D1" "--format" "json"
                                             (root-arg root))
      (is (= 0 code))
      (let ((json (shasht:read-json out)))
        (is (equal "TEST-D1" (gethash "record" json)))
        (is (= 12 (gethash "end" (gethash "front_matter" json))))
        (is (= 4 (length (gethash "sections" json))))))
    (multiple-value-bind (code out err) (run-cli "outline" "TEST-0404" (root-arg root))
      (is (= 1 code))
      (is (string= "" out))
      (is (search "not defined" err)))
    (is (= 2 (run-cli "outline" "not-an-id" (root-arg root))))
    (is (= 2 (run-cli "outline" (root-arg root))))))

(test refs-command
  (with-temp-repository (root *reference-files*)
    (multiple-value-bind (code out) (run-cli "refs" "TEST-D1" (root-arg root))
      (is (= 0 code))
      (is (search "TEST-D1 is a decision record defined at doc/Plan.A.md:17." out))
      (is (search "Register listings (1):" out))
      (is (search "3 references in 2 documents." out)))
    (multiple-value-bind (code out) (run-cli "refs" "TEST-0001" "--format" "json"
                                             (root-arg root))
      (is (= 0 code))
      (let ((json (shasht:read-json out)))
        (is (equal "document" (gethash "kind" (gethash "defined" json))))
        (is (= 6 (gethash "references" (gethash "summary" json))))
        (is (equal '("basis" "relation" "link" "link" "mention" "mention")
                   (map 'list (lambda (r) (gethash "kind" r)) (gethash "references" json))))))
    (multiple-value-bind (code out err) (run-cli "refs" "TEST-0404" (root-arg root))
      (is (= 1 code))
      (is (search "No references." out))
      (is (search "neither defined nor referenced" err)))
    (is (= 2 (run-cli "refs" "lowercase-id" (root-arg root))))))

;;; init, manifest, and paths relative to --root

(test init-writes-a-manifest
  (with-git-repository (root (list (list "docs/Plan.A.md" (doc :id "ALPHA-DRAFT-a"))
                                   (list "docs/Plan.B.md" (doc :id "BETA-0001")))
                             :name "Ada")
    (multiple-value-bind (code out) (run-cli "init" "--dry-run" (root-arg root))
      (is (= 0 code))
      (is (search "(:namespaces (\"ALPHA\" \"BETA\")" out) "inferred from the documents")
      (is (search ":doc-directory \"docs/\"" out))
      (is (search ":stewards ((:namespace \"ALPHA\" :steward \"Ada\" :approval :second-reviewer)" out))
      (is (not (uiop:file-exists-p (root-file root "compass.sexp")))))
    (multiple-value-bind (code out) (run-cli "init" "--namespace" "ALPHA" "--solo"
                                             "--federation" "ORIGIN=../origin"
                                             "--steward" "Andrew Sengul" (root-arg root))
      (is (= 0 code))
      (is (search "Wrote compass.sexp: namespace ALPHA, documents in docs/, steward Andrew Sengul."
                  out)))
    (multiple-value-bind (manifest problems) (read-manifest (root-file root "compass.sexp"))
      (is (null problems))
      (is (equal '("ALPHA") (manifest-namespaces manifest)))
      (is (equal "docs/" (manifest-doc-directory manifest)))
      (is (equal "../origin" (federation-entry-path (first (manifest-federation manifest)))))
      (is (eq :solo (steward-approval (first (manifest-stewards manifest))))))
    (multiple-value-bind (code out err) (run-cli "init" (root-arg root))
      (is (= 1 code))
      (is (string= "" out))
      (is (search "already exists; edit it by hand" err))))
  (with-temp-repository (root (list (list "notes.txt" "x")))
    (multiple-value-bind (code out err) (run-cli "init" (root-arg root))
      (declare (ignore out))
      (is (= 2 code))
      (is (search "pass --namespace NS" err)))
    (is (= 2 (run-cli "init" "--namespace" "lower" (root-arg root))))
    (is (= 2 (run-cli "init" "--namespace" "X" "--federation" "nope" (root-arg root))))
    (is (= 0 (run-cli "init" "--namespace" "X" (root-arg root))))
    (is (search "(:namespaces (\"X\")" (read-file root "compass.sexp")))
    (is (not (search ":stewards" (read-file root "compass.sexp"))) "no Git, no steward")))

(test manifest-json
  (with-temp-repository (root (list (list "compass.sexp"
                                          (lines "(:namespaces (\"TEST\") :doc-directory \"notes\""
                                                 " :federation ((:namespace \"O\" :path \"../o\"))"
                                                 " :commands ((:name :test :shell \"make test\"))"
                                                 " :stewards ((:namespace \"TEST\" :steward \"Ada\" :approval :solo)))"))))
    (multiple-value-bind (code out) (run-cli "manifest" "--json" (root-arg root))
      (is (= 0 code))
      (let ((json (shasht:read-json out)))
        (is (equalp #("TEST") (gethash "namespaces" json)))
        (is (equal "notes/" (gethash "doc_directory" json)))
        (is (equal "notes/REGISTRY.sexp" (gethash "ledger" json)))
        (is (equal "../o" (gethash "path" (aref (gethash "federation" json) 0))))
        (is (equal "shell" (gethash "kind" (aref (gethash "commands" json) 0))))
        (is (equal "test" (gethash "name" (aref (gethash "commands" json) 0))))
        (is (equal "solo" (gethash "approval" (aref (gethash "stewards" json) 0))))))
    (is (= 2 (run-cli "manifest" (root-arg root))) "JSON only"))
  (with-temp-repository (root (list (list "compass.sexp" "(:namespaces (\"lower\"))")))
    (multiple-value-bind (code out err) (run-cli "manifest" "--json" (root-arg root))
      (is (= 1 code))
      (is (gethash "namespaces" (shasht:read-json out)))
      (is (search "manifest/valid" err))))
  (with-temp-repository (root (list (list "notes.txt" "x")))
    (is (= 1 (run-cli "manifest" "--json" (root-arg root))))))

(test paths-relative-to-root
  (with-temp-repository (root (list (list "doc/Plan.A.md" (doc :created "2026-10-09"))))
    (let ((*default-pathname-defaults* (uiop:temporary-directory)))
      (multiple-value-bind (code out) (run-cli "check" (root-arg root) "doc/Plan.A.md")
        (is (= 0 code))
        (is (search "Checked 1 document" out)))
      (is (= 2 (run-cli "check" (root-arg root) "doc/Nope.md"))))))