;;;; test-cli.lisp — Tests for the command line: exit codes, output formats, and usage errors

(in-package #:compass.tests)

(def-suite cli :in compass)
(in-suite cli)

(defun run-cli (&rest args)
  "Run compass with ARGS. Return the exit code, standard output, and error output."
  (let* ((out (make-string-output-stream))
         (err (make-string-output-stream))
         (code (let ((*standard-output* out) (*error-output* err))
                 (main args :exit nil))))
    (values code (get-output-stream-string out) (get-output-stream-string err))))

(defun root-arg (root) (format nil "--root=~a" (uiop:native-namestring root)))

(test check-exit-codes
  (with-temp-repository (root (list (list "doc/Plan.A.md" (doc))))
    (multiple-value-bind (code out) (run-cli "check" (root-arg root))
      (is (= 0 code))
      (is (search "Checked 1 document: 0 errors, 0 warnings." out))))
  (with-temp-repository (root (list (list "doc/Plan.A.md" (doc :genre "Nonsense"))))
    (multiple-value-bind (code out) (run-cli "check" (root-arg root))
      (is (= 1 code))
      (is (search "doc/Plan.A.md:4:8: error vocab/genre:" out))))
  (with-temp-repository (root (list (list "doc/Plan.A.md" (doc :extra '("colour: blue")))))
    (is (= 0 (run-cli "check" (root-arg root))))
    (is (= 1 (run-cli "check" "--strict" (root-arg root))))))

(test check-json
  (with-temp-repository (root (list (list "doc/Plan.A.md" (doc :scope "team"))))
    (multiple-value-bind (code out) (run-cli "check" "--format" "json" (root-arg root))
      (is (= 1 code))
      (let* ((json (shasht:read-json out))
             (findings (gethash "findings" json)))
        (is (equal "compass" (gethash "tool" json)))
        (is (= 1 (gethash "errors" (gethash "summary" json))))
        (is (equal "vocab/scope" (gethash "rule" (aref findings 0))))
        (is (equal "doc/Plan.A.md" (gethash "path" (aref findings 0))))))))

(test check-rule-selection-and-paths
  (with-temp-repository (root (list (list "doc/Plan.A.md" (doc :scope "team"))
                                    (list "doc/Plan.B.md" (doc :id "TEST-0002"
                                                               :genre "Nonsense"))))
    (is (= 1 (run-cli "check" "--rule" "vocab/scope" (root-arg root))))
    (is (= 0 (run-cli "check" "--rule" "fm" (root-arg root))))
    (is (= 0 (run-cli "check" "--exclude" "vocab" (root-arg root))))
    (let ((*default-pathname-defaults* root))
      (multiple-value-bind (code out)
          (run-cli "check" (root-arg root)
                   (uiop:native-namestring (merge-pathnames "doc/Plan.A.md" root)))
        (is (= 1 code))
        (is (not (search "Plan.B.md" out)))))))

(test show-and-next
  (with-temp-repository (root (list (list "doc/Plan.A.md" (doc :body (lines "# T" "## Part" "Text.")))))
    (multiple-value-bind (code out) (run-cli "show" "TEST-0001#part" (root-arg root))
      (is (= 0 code))
      (is (search (lines "## Part" "Text.") out)))
    (multiple-value-bind (code out err) (run-cli "show" "TEST-0404" (root-arg root))
      (is (= 1 code))
      (is (string= "" out))
      (is (search "not defined" err)))
    (multiple-value-bind (code out err) (run-cli "next" "TEST" (root-arg root))
      (is (= 0 code))
      (is (equal (lines "TEST-0002") out))
      (is (search "advisory" err)))))

(test usage-errors
  (is (= 2 (run-cli)))
  (is (= 2 (run-cli "frobnicate")))
  (is (= 2 (run-cli "check" "--colour")))
  (is (= 2 (run-cli "check" "--format" "xml")))
  (is (= 2 (run-cli "check" "--rule" "no/such-rule")))
  (is (= 2 (run-cli "next" "lowercase")))
  (multiple-value-bind (code out err) (run-cli "check" "--format")
    (declare (ignore out))
    (is (= 2 code))
    (is (search "needs a value" err))))

(test help-version-rules
  (multiple-value-bind (code out) (run-cli "help")
    (is (= 0 code))
    (dolist (command '("check" "show" "outline" "refs" "index" "next" "rules" "version"))
      (is (search (format nil "  ~a " command) out) "help lists ~a" command)))
  (multiple-value-bind (code out) (run-cli "version")
    (is (= 0 code))
    (is (starts-with-p (format nil "compass ~a" +version+) out)))
  (multiple-value-bind (code out) (run-cli "rules" "--format" "json")
    (is (= 0 code))
    (let ((rules (shasht:read-json out)))
      (is (find "memo/basis" rules :key (lambda (r) (gethash "name" r)) :test #'equal))
      (is (find "fm/syntax" rules :key (lambda (r) (gethash "name" r)) :test #'equal)))))

(test check-rejects-paths-outside-the-corpus
  (with-temp-repository (root (list (list "doc/Plan.A.md" (doc))
                                    (list "doc/Plan.B.md" (doc :id "TEST-0002"))
                                    (list "templates/X.md" (lines "# Not a document"))))
    (flet ((path (relative) (uiop:native-namestring (merge-pathnames relative root))))
      (multiple-value-bind (code out err) (run-cli "check" (root-arg root)
                                                   (path "templates/X.md"))
        (is (= 2 code))
        (is (string= "" out))
        (is (search "templates/X.md is not a document of this corpus" err)))
      (multiple-value-bind (code out err) (run-cli "check" (root-arg root) (path "templates/"))
        (declare (ignore out))
        (is (= 2 code))
        (is (search "contains no documents" err)))
      (multiple-value-bind (code out) (run-cli "check" (root-arg root) (path "doc/Plan.A.md"))
        (is (= 0 code))
        (is (search "Checked 1 document of 2:" out)))
      (multiple-value-bind (code out) (run-cli "check" (root-arg root) (path "doc/"))
        (is (= 0 code))
        (is (search "Checked 2 documents:" out)))
      (with-temp-repository (elsewhere (list (list "doc/Plan.Z.md" (doc))))
        (multiple-value-bind (code out err)
            (run-cli "check" (root-arg root)
                     (uiop:native-namestring (merge-pathnames "doc/Plan.Z.md" elsewhere)))
          (declare (ignore out))
          (is (= 2 code))
          (is (search "outside the repository" err)))))))

(test empty-corpus
  (with-temp-repository (root (list (list "notes.txt" "nothing here")))
    (multiple-value-bind (code out err) (run-cli "check" (root-arg root))
      (is (= 0 code))
      (is (search "Checked 0 documents" out))
      (is (search "no documents found" err)))
    (multiple-value-bind (code out err) (run-cli "index" (root-arg root))
      (declare (ignore out))
      (is (= 2 code))
      (is (search "no index was written" err))
      (is (not (probe-file (merge-pathnames "doc/INDEX.md" root)))))
    (is (= 0 (run-cli "index" "--stdout" (root-arg root))))))

(test outline-command
  (with-temp-repository (root *reference-files*)
    (multiple-value-bind (code out) (run-cli "outline" "TEST-0001" (root-arg root))
      (is (= 0 code))
      (is (search "TEST-0001 — A test document" out))
      (is (search "doc/Plan.A.md; Plan, Draft" out))
      (is (search "### TEST-D1 — Use a ledger  #test-d1--use-a-ledger" out)))
    (multiple-value-bind (code out) (run-cli "outline" "TEST-D1" "--format" "json"
                                             (root-arg root))
      (is (= 0 code))
      (let ((json (shasht:read-json out)))
        (is (equal "TEST-D1" (gethash "record" json)))
        (is (= 12 (gethash "end" (gethash "front_matter" json))))
        (is (= 4 (length (gethash "sections" json))))))
    (multiple-value-bind (code out err) (run-cli "outline" "TEST-0404" (root-arg root))
      (is (= 1 code))
      (is (string= "" out))
      (is (search "not defined" err)))
    (is (= 2 (run-cli "outline" "not-an-id" (root-arg root))))
    (is (= 2 (run-cli "outline" (root-arg root))))))

(test refs-command
  (with-temp-repository (root *reference-files*)
    (multiple-value-bind (code out) (run-cli "refs" "TEST-D1" (root-arg root))
      (is (= 0 code))
      (is (search "TEST-D1 is a decision record defined at doc/Plan.A.md:17." out))
      (is (search "Register listings (1):" out))
      (is (search "3 references in 2 documents." out)))
    (multiple-value-bind (code out) (run-cli "refs" "TEST-0001" "--format" "json"
                                             (root-arg root))
      (is (= 0 code))
      (let ((json (shasht:read-json out)))
        (is (equal "document" (gethash "kind" (gethash "defined" json))))
        (is (= 6 (gethash "references" (gethash "summary" json))))
        (is (equal '("basis" "relation" "link" "link" "mention" "mention")
                   (map 'list (lambda (r) (gethash "kind" r)) (gethash "references" json))))))
    (multiple-value-bind (code out err) (run-cli "refs" "TEST-0404" (root-arg root))
      (is (= 1 code))
      (is (search "No references." out))
      (is (search "neither defined nor referenced" err)))
    (is (= 2 (run-cli "refs" "lowercase-id" (root-arg root))))))
