;;;; test-corpus.lisp — Tests for discovery, lookup, show, index, and next

(in-package #:compass.tests)

(def-suite corpus :in compass)
(in-suite corpus)

(defparameter *sample-files*
  (list (list "Compass.md" (doc :id "TEST-0001" :genre "Spec" :status "Draft"
                                :body (lines "# Standard" "## Scope" "In scope.")))
        (list "README.md" (lines "# Readme, a fixture without front-matter"))
        (list "doc/README.md" (lines "# Doc readme"))
        (list "doc/INDEX.md" (lines "<!-- generated -->"))
        (list "doc/Plan.A.md"
              (doc :id "TEST-DRAFT-alpha"
                   :extra '("decisions:" "  - TEST-DRAFT-alpha-D1" "  - TEST-D3")
                   :body (lines "# Alpha" "## Settled Decisions" ""
                                "### TEST-DRAFT-alpha-D1 — Use a ledger" ""
                                "**Status:** Accepted" "" "Because."
                                "" "### TEST-D3 — An older decision" ""
                                "**Status:** Accepted" "" "## Roadmap" "1. Build.")))
        (list "doc/sub/Log.B.md" (doc :id "TEST-0004" :genre "Log" :status "Accepted"))))

(test discovery
  (with-temp-repository (root *sample-files*)
    (let ((corpus (load-corpus root)))
      (is (equal '("Compass.md" "doc/Plan.A.md" "doc/sub/Log.B.md")
                 (mapcar #'document-path (corpus-documents corpus))))
      (is (null (corpus-load-findings corpus)))
      (is (equal '("TEST") (corpus-namespaces corpus))))))

(test repository-root
  (with-temp-repository (root (list (list "compass.sexp" "(:namespaces (\"TEST\"))")
                                    (list "doc/deep/x.md" "x")))
    (is (uiop:pathname-equal root
                             (find-repository-root (merge-pathnames "doc/deep/" root))))))

(test lookup-and-resolve
  (with-temp-repository (root *sample-files*)
    (let ((corpus (load-corpus root)))
      (is (equal "doc/Plan.A.md" (document-path (find-document corpus "TEST-DRAFT-alpha"))))
      (is (equal "Use a ledger" (record-title (find-record corpus "TEST-DRAFT-alpha-D1"))))
      (is (typep (resolve corpus "TEST-0001#scope") 'section))
      (is (null (resolve corpus "TEST-0001#nowhere")))
      (is (null (resolve corpus "TEST-0099"))))))

(test show-text
  (with-temp-repository (root *sample-files*)
    (let ((corpus (load-corpus root)))
      (multiple-value-bind (text path first last) (show corpus "TEST-DRAFT-alpha-D1")
        (is (equal "doc/Plan.A.md" path))
        (is (= 17 first))
        (is (= 21 last))
        (is (starts-with-p "### TEST-DRAFT-alpha-D1 — Use a ledger" text))
        (is (search "Because." text))
        (is (not (search "older decision" text))))
      (multiple-value-bind (text) (show corpus "TEST-0001#scope")
        (is (equal (lines "## Scope" "In scope.") text)))
      (is (null (show corpus "TEST-0404"))))))

(test index-generation
  (with-git-repository (root *sample-files*)
    (let* ((corpus (load-corpus root))
           (text (generate-index corpus)))
      (is (starts-with-p "<!-- Generated by `compass index`" text))
      (is (search "| [TEST-0001](../Compass.md) |" text))
      (is (search "| [TEST-0004](sub/Log.B.md) |" text))
      (is (search "Table: Documents in the TEST namespace." text))
      (is (search "[TEST-D3](Plan.A.md#test-d3--an-older-decision)" text))
      ;; Canonical identifiers come before provisional ones.
      (is (< (search "TEST-0004" text) (search "TEST-DRAFT-alpha]" text)))
      (is (equal "doc/INDEX.md" (write-index corpus)))
      (is (equal text (read-text-file (root-file root "doc/INDEX.md"))))
      ;; The index is not a document, and its links resolve.
      (let ((after (load-corpus root)))
        (is (= 3 (length (corpus-documents after))))
        (is (null (check-corpus after)))))))

(test next-identifier-without-a-ledger
  (with-temp-repository (root *sample-files*)
    (let ((corpus (load-corpus root)))
      (multiple-value-bind (id ledger-p) (next-identifier corpus "TEST" :document)
        (is (equal "TEST-0005" id))
        (is-false ledger-p))
      (is (equal "TEST-D4" (next-identifier corpus "TEST" :decision)))
      (is (equal "TEST-M1" (next-identifier corpus "TEST" :memo)))
      (is (equal "OTHER-0001" (next-identifier corpus "OTHER" :document))))))

;;; outline and refs

(defparameter *reference-files*
  (list (list "doc/Plan.A.md"
              (doc :id "TEST-0001"
                   :extra '("decisions:" "  - TEST-D1")
                   :body (lines "# Alpha" ""
                                "## Settled Decisions" ""
                                "### TEST-D1 — Use a ledger" ""
                                "**Status:** Accepted" ""
                                "See [the roadmap](#roadmap) and TEST-D1 again."
                                "Alpha names TEST-0001, its own id." "" ""
                                "## Roadmap" ""
                                "1. Build.")))
        (list "doc/Plan.B.md"
              (doc :id "TEST-0002"
                   :extra '("relates-to:" "  - TEST-0001" "decisions:" "  - TEST-D1")
                   :body (lines "# Beta" ""
                                "[TEST-0001](Plan.A.md) is the plan; TEST-0001 again."
                                "See [the decision](Plan.A.md#test-d1--use-a-ledger)."
                                "Mentions TEST-0001 in prose."
                                "" "```" "TEST-0001 in a fence" "```" ""
                                "<!-- TEST-0001 in a comment -->"
                                "See TEST-0001#roadmap for the plan's steps.")))
        (list "doc/Memo.C.md"
              (doc :id "TEST-0003" :genre "Memo" :status "Current" :scope "component"
                   :extra '("memos:" "  - TEST-M1")
                   :body (lines "# C: Memos" "" "## Memos" ""
                                "### TEST-M1 — The ledger is append-only" ""
                                "**Status:** Draft"
                                "**Read-if:** changing the ledger"
                                "**Basis:** decided in TEST-0001; reviewed")))))

(defun reference-kinds (references)
  (mapcar (lambda (r) (list (inbound-reference-kind r) (inbound-reference-path r)))
          references))

(test outline-of-a-document
  (with-temp-repository (root *reference-files*)
    (let* ((corpus (load-corpus root))
           (outline (document-outline corpus "TEST-0001")))
      (is (equal "doc/Plan.A.md" (outline-path outline)))
      (is (equal "Plan" (outline-genre outline)))
      (is (= 12 (outline-front-matter-end outline)))
      (is (equal '("alpha" "settled-decisions" "test-d1--use-a-ledger" "roadmap")
                 (mapcar #'outline-entry-anchor (outline-entries outline))))
      (let ((decisions (second (outline-entries outline)))
            (record (third (outline-entries outline))))
        (is (= 15 (outline-entry-start decisions)))
        (is (= 22 (outline-entry-end decisions)) "trailing blank lines are trimmed")
        (is (equal "TEST-D1" (outline-entry-record record)))
        (is (equal "TEST-D1 — Use a ledger" (outline-entry-text record))))
      ;; Line ranges agree with show.
      (multiple-value-bind (text path first last) (show corpus "TEST-0001#settled-decisions")
        (declare (ignore text path))
        (is (= 15 first))
        (is (= 22 last))))))

(test outline-of-a-record-and-a-section
  (with-temp-repository (root *reference-files*)
    (let ((corpus (load-corpus root)))
      (let ((outline (document-outline corpus "TEST-D1")))
        (is (equal "TEST-0001" (outline-id outline)))
        (is (equal "TEST-D1" (outline-record outline)))
        (is (equal "test-d1--use-a-ledger" (outline-focus outline)))
        (is (= 4 (length (outline-entries outline)))))
      (let ((outline (document-outline corpus "TEST-0001#settled-decisions")))
        (is (equal '("settled-decisions" "test-d1--use-a-ledger")
                   (mapcar #'outline-entry-anchor (outline-entries outline)))))
      (is (null (document-outline corpus "TEST-0001#nowhere")))
      (is (null (document-outline corpus "TEST-0404"))))))

(test refs-to-a-document
  (with-temp-repository (root *reference-files*)
    (multiple-value-bind (references definition)
        (find-references (load-corpus root) "TEST-0001")
      (is (equal "doc/Plan.A.md" (document-path definition)))
      (is (equal '((:basis "doc/Memo.C.md")
                   (:relation "doc/Plan.B.md")
                   (:link "doc/Plan.B.md")
                   (:link "doc/Plan.B.md")
                   (:mention "doc/Plan.B.md")
                   (:mention "doc/Plan.B.md"))
                 (reference-kinds references))
          "~s" (reference-kinds references))
      (let ((relation (find :relation references :key #'inbound-reference-kind)))
        (is (equal "relates-to" (inbound-reference-field relation)))
        (is (equal "TEST-0002" (inbound-reference-source relation)))
        (is (= 11 (inbound-reference-line relation)) "the line of the list item")))))

(test refs-to-a-record
  (with-temp-repository (root *reference-files*)
    (multiple-value-bind (references definition)
        (find-references (load-corpus root) "TEST-D1")
      (is (equal "TEST-D1" (record-id definition)))
      (is (equal '((:mention "doc/Plan.A.md")
                   (:register "doc/Plan.B.md")
                   (:link "doc/Plan.B.md"))
                 (reference-kinds references))
          "~s" (reference-kinds references))
      (is (= 21 (inbound-reference-line (first references)))
          "the host's mention, not its heading or its own listing"))))

(test refs-to-a-section-and-undefined-ids
  (with-temp-repository (root *reference-files*)
    (let ((corpus (load-corpus root)))
      (multiple-value-bind (references definition)
          (find-references corpus "TEST-0001#roadmap")
        (is (typep definition 'section))
        (is (equal '((:link "doc/Plan.A.md") (:mention "doc/Plan.B.md"))
                   (reference-kinds references))))
      (multiple-value-bind (references definition) (find-references corpus "TEST-0404")
        (is (null references))
        (is (null definition))))))

(test refs-to-an-undefined-but-referenced-id
  (with-temp-repository (root (list (list "doc/Plan.A.md"
                                          (doc :extra '("relates-to:" "  - TEST-0009")))))
    (multiple-value-bind (references definition)
        (find-references (load-corpus root) "TEST-0009")
      (is (null definition))
      (is (equal '((:relation "doc/Plan.A.md")) (reference-kinds references))))))
