;;;; index.lisp — Generate the namespace index, and preview the next identifier
;;;;
;;;; Read-if: changing the generated INDEX.md, or how `compass next` computes a number
;;;; See: COMPASS-DRAFT-toolchain-D6, COMPASS-DRAFT-toolchain-D3
;;;; Invariant: INDEX.md is generated; its banner tells readers not to edit it
;;;; Invariant: before the ledger exists, next-identifier is advisory
;;;; Tests: tests/test-corpus.lisp

(in-package #:compass.corpus)

(defparameter +index-banner+
  "<!-- Generated by `compass index` — do not edit. -->")

(defun index-relative-path (corpus)
  (concatenate 'string (corpus-doc-directory corpus) "INDEX.md"))

(defun relative-link (from-directory to-path)
  "A relative link from the directory FROM-DIRECTORY (ending in /) to TO-PATH,
both relative to the repository root."
  (let* ((from (remove "" (uiop:split-string from-directory :separator "/")
                       :test #'string=))
         (to (uiop:split-string to-path :separator "/")))
    (loop while (and from (rest to) (string= (first from) (first to)))
          do (pop from) (pop to))
    (format nil "~{~a~}~a"
            (make-list (length from) :initial-element "../")
            (string-join to "/"))))

(defun cell (string)
  "STRING escaped for a Markdown table cell."
  (if (or (null string) (string= string ""))
      "—"
      (ppcre:regex-replace-all "\\|" (substitute #\Space #\Newline string) "\\\\|")))

(defun identifier-sort-key (id-string)
  (let ((id (parse-identifier id-string)))
    (if id
        (list (if (identifier-provisional-p id) 1 0)
              (if (identifier-provisional-p id) 0 (or (identifier-serial id) 0))
              (or (identifier-slug id) "")
              (if (identifier-provisional-p id) (or (identifier-serial id) 0) 0))
        (list 2 0 id-string 0))))

(defun key< (a b)
  (loop for x in a for y in b
        do (cond ((and (numberp x) (numberp y))
                  (cond ((< x y) (return t)) ((> x y) (return nil))))
                 (t (cond ((string< x y) (return t)) ((string> x y) (return nil)))))
        finally (return nil)))

(defun identifier< (a b)
  (key< (identifier-sort-key a) (identifier-sort-key b)))

(defun record-anchor (record)
  (let ((section (find (location-line record) (document-sections (record-document record))
                       :key #'location-line)))
    (and section (section-anchor section))))

(defun genre-cell (document)
  (let ((genre (document-genre document))
        (subtype (document-field-string document "subtype")))
    (if subtype (format nil "~a (~a)" genre subtype) genre)))

(defun generate-index (corpus &key namespace)
  "The text of the generated index for NAMESPACE, or for every namespace."
  (let* ((directory (corpus-doc-directory corpus))
         (documents (remove-if-not #'document-identifier (corpus-documents corpus)))
         (namespaces (if namespace
                         (list namespace)
                         (sort (remove-duplicates (mapcar #'document-namespace documents)
                                                  :test #'string=)
                               #'string<))))
    (with-output-to-string (out)
      (format out "~a~%# Index~%~%" +index-banner+)
      (format out "Generated by `compass index` from the front-matter of this ~
                   repository's documents~%and from the headings of their decision, ~
                   open-question, and memo records.~%")
      (dolist (ns namespaces)
        (let ((docs (sort (remove ns documents :key #'document-namespace
                                               :test-not #'string=)
                          #'identifier< :key #'document-id))
              (records '()))
          (dolist (document docs)
            (dolist (record (document-records document))
              (when (string= (identifier-namespace (record-identifier record)) ns)
                (push record records))))
          (setf records
                (sort records
                      (lambda (a b)
                        (let ((ka (position (record-kind a) '(:decision :open-question :memo)))
                              (kb (position (record-kind b) '(:decision :open-question :memo))))
                          (if (= ka kb) (identifier< (record-id a) (record-id b)) (< ka kb))))))
          (format out "~%## ~a~%~%Table: Documents in the ~a namespace.~%~%" ns ns)
          (format out "| ID | Title | Genre | Scope | Status | Component |~%")
          (format out "|---|---|---|---|---|---|~%")
          (dolist (document docs)
            (format out "| [~a](~a) | ~a | ~a | ~a | ~a | ~a |~%"
                    (document-id document)
                    (relative-link directory (document-path document))
                    (cell (document-title document)) (cell (genre-cell document))
                    (cell (document-scope document)) (cell (document-status document))
                    (cell (document-component document))))
          (when records
            (format out "~%Table: Decision, open-question, and memo records in the ~a ~
                         namespace.~%~%" ns)
            (format out "| ID | Kind | Title | Status | Host |~%")
            (format out "|---|---|---|---|---|~%")
            (dolist (record records)
              (let ((host (record-document record)))
                (format out "| [~a](~a~@[#~a~]) | ~a | ~a | ~a | ~a |~%"
                        (record-id record)
                        (relative-link directory (document-path host))
                        (record-anchor record)
                        (register-kind-label (find-register-kind (record-kind record)))
                        (cell (record-title record))
                        (cell (record-field record "Status"))
                        (cell (document-id host)))))))))))

(defun write-index (corpus &key namespace)
  "Write the generated index to INDEX.md in the document directory. Return its
repository-relative path."
  (let ((path (index-relative-path corpus)))
    (write-text-file (root-file (corpus-root corpus) path)
                     (generate-index corpus :namespace namespace))
    path))

(defun next-identifier (corpus namespace kind)
  "Preview the next canonical identifier of KIND in NAMESPACE, from the highest
canonical number defined in the corpus. Return the identifier, and T to say the
result is advisory: until the ledger exists (v0.2), a corpus scan cannot see
numbers allocated on other branches."
  (let ((highest 0))
    (flet ((consider (string)
             (let ((id (parse-identifier string)))
               (when (and id (not (identifier-provisional-p id))
                          (string= (identifier-namespace id) namespace)
                          (eq (identifier-kind id) kind))
                 (setf highest (max highest (identifier-serial id)))))))
      (dolist (document (corpus-documents corpus))
        (consider (document-id document))
        (dolist (record (document-records document))
          (consider (record-id record)))
        (dolist (kind-spec (register-kinds))
          (mapc #'consider
                (node-identifiers (document-field-node document
                                                       (register-kind-field kind-spec)))))))
    (values (format-canonical-identifier namespace kind (1+ highest)) t)))
